### New Thread
POST http://localhost:8000/api/new
Accept: application/json

#Manual step substitute in thread id and run id from Request 1: 
@thread_id = thread_oDjXfAROCT2BNxbs59S3UzhO
@run_id = run_j2yCYuvPTFSxWgBFhwsq68g2

### Retrieve Thread
GET http://localhost:8000/api/threads/{{thread_id}}
Accept: application/json

### Run status
GET http://localhost:8000/api/threads/{{thread_id}}/runs/{{run_id}}
Accept: application/json

### New Reply
POST http://localhost:8000/api/threads/{{thread_id}}
Accept: application/json
Content-Type: application/json

{ "content": "What products doees Protea AI have?" }


### Submit Tool Output
POST http://localhost:8000/api/threads/{{thread_id}}/runs/{{run_id}}/tool
Accept: application/json
Content-Type: application/json

[
    {
        "tool_call_id": "call_WNpt3enka45nnK8MMFkSDetd",
        "output": "{'success': true}"
    }
]